@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

class BuildStationUI {
}

class BuildStationController {
    + BuildStationController()
    + getAvailableStationTypes() : List<StationType>
    + getStationTypeByID(stationTypeID : String) : StationType
    + proposeStationName(location : Object, stationType : StationType) : String
    - getCurrentMapFromSession() : Map
    - getProposedStationName(nearestCity : String, stationType : StationType) : String
    + buildStation(stationType : StationType, location : Object, center : Object, name : String)
}

class Repositories {
    - Repositories()
    + {static} getInstance()
    + getStationRepository()
    + getMapRepository()
}

class StationRepository {
    + getAvailableStationTypes() : List<StationType>
    + getStationTypeByID(stationTypeID : String) : StationType
    + calculateGeometricCenter(stationType : StationType) : Object
    + getProposedStationName(nearestCity : String, stationType : StationType) : String
    + buildStation(stationType : StationType, location : Object, center : Object, name : String) : Station
    + addStation(station : Station)
}

class MapRepository {
    + getCurrentMap() : Map
}

class Map {
    + getNearestCityFromLocation(location : Object) : String
}

class Station {
    - name : String
    - type : StationType
    - location : Object
    - center : Object
    + Station(type, location, center, name)
}

class ApplicationSession {
    - ApplicationSession()
    + {static} getInstance()
    + getCurrentSession()
}

BuildStationUI ..> BuildStationController
BuildStationController .> Repositories
Repositories -> "1" Repositories : instance
Repositories --> "1" StationRepository : stationRepository
Repositories --> "1" MapRepository : mapRepository
BuildStationController ..> StationRepository
BuildStationController ..> MapRepository
BuildStationController ..> Map
BuildStationController ..> ApplicationSession
StationRepository --> "*" Station : stations
MapRepository --> "*" Map : maps
ApplicationSession -> "1" ApplicationSession : instance

@enduml