@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

class UpgradeStationUI {
}

class UpgradeStationController {
    + UpgradeStationController()
    + getStationsAvailableForUpgrade() : List<Station>
    + getAvailableUpgradeBuildings(station : Station) : List<UpgradeBuilding>
    + getUpgradeBuildingByID(upgradeBuildingID : String) : UpgradeBuilding
    + applyUpgrade(station : Station, upgradeBuilding : UpgradeBuilding)
}

class Repositories {
    - Repositories()
    + {static} getInstance()
    + getStationRepository()
    + getUpgradeBuildingRepository()
}

class StationRepository {
    + getStationsAvailableForUpgrade() : List<Station>
    + getStationByID(stationID : String) : Station
}

class UpgradeBuildingRepository {
    + getAvailableUpgradeBuildings(station : Station, installedUpgradesList : List<UpgradeBuilding>, currentDate : Date) : List<UpgradeBuilding>
    + getUpgradeBuildingByID(upgradeBuildingID : String) : UpgradeBuilding
}

class Station {
    + getUpgradesInstalled(station : Station) : List<UpgradeBuilding>
    + replaceBuilding(installedUpgrade : UpgradeBuilding, upgradeBuilding : UpgradeBuilding, station : Station)
    + addBuilding(upgradeBuilding : UpgradeBuilding, station : Station)
}

class UpgradeBuilding {
    + isInSameExclusivityGroup(upgradeBuilding : UpgradeBuilding, installedUpgrade : UpgradeBuilding) : boolean
}

class Scenario {
    + getCurrentDate() : Date
}

class ApplicationSession {
    - ApplicationSession()
    + {static} getInstance()
    + getCurrentSession()
}

UpgradeStationUI ..> UpgradeStationController
UpgradeStationController .> Repositories
Repositories -> "1" Repositories : instance
Repositories --> "1" StationRepository : stationRepository
Repositories --> "1" UpgradeBuildingRepository : upgradeBuildingRepository
UpgradeStationController ..> StationRepository
UpgradeStationController ..> UpgradeBuildingRepository
UpgradeStationController ..> Scenario
UpgradeStationController ..> ApplicationSession
StationRepository --> "*" Station : stations
UpgradeBuildingRepository --> "*" UpgradeBuilding : upgradeBuildings
ApplicationSession --> "1" ApplicationSession : instance

@enduml