@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Player" as Player
participant ":System" as System

activate Player

    Player -> System : requests to upgrade a station
    activate System

        System --> Player : shows stations available for upgrade
    deactivate System

    Player -> System : selects a station
    activate System

        System --> Player : requests confirmation
    deactivate System

    Player -> System : confirms upgrade
    activate System

        System --> Player : displays upgrade success
    deactivate System
@enduml