@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Player" as Player
participant ":System" as System

activate Player

    Player -> System : requests to build a station
    activate System

        System --> Player : shows available station types (Depot, Station, Terminal)
    deactivate System

    Player -> System : selects station type
    activate System

        opt station type is "Station"
            System --> Player : requests for station's center (NE, SE, NW, SW)
            deactivate System

            Player -> System : provides station's center
            activate System
        end

        System --> Player : requests for station's location
    deactivate System

    Player -> System : provides station's location
    activate System

        System --> Player : proposes station name
    deactivate System

    alt player accepts proposed name
        Player -> System : confirms station name
        activate System

            System --> Player : displays station's name, location, and center and requests final confirmation
        deactivate System

        Player -> System : confirms all data
        activate System

            System --> Player : displays operation success
        deactivate System

     else \t \t player rejects proposed name

        Player -> System : rejects proposed name
        activate System

            System --> Player : requests alternative name
        deactivate System

        Player -> System : provides alternative name
        activate System

            System --> Player : displays station's name, location, and center and requests final confirmation
        deactivate System

        Player -> System : confirms all data
        activate System

            System --> Player : displays operation success
        deactivate System
    end

deactivate Player
@enduml