@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model - Railway Simulation

class Map {
size
name
}

class City {
   name
   numberOfHouseBlocks
}

class Location{
X coordinates
Y coordinates
}

class Industry{
type
}

class Resource{
name
type
}

class ScenarioEditor{
    timeRestrictions
    technologicalRestrictions
    historicalRestrictions
}

class Scenario{

}

class ProductOwner{

}

class Editor{

}

class Player{

}

class Simulator{
status
}

class RailwayNetwork{

}

class Station{
name
type
economic radius
cost
status
}

class Train{

}

class Route{

}

class Cargo{
deliverValue
}

class RailwayLine{
length
lineType
electrified
}

class Locomotive{
type
power
acceleration
topSpeed
startYearOfOperation
fuelCost
maintenancePerYear
acquisitionPrice
cost
}

class Carriage{

}

class CargoType{
type
}


Editor "1" --- "1..*" Map : creates >
Editor "1" --- "1..*" Scenario: creates >
Editor "1" --- "1..*" Industry : adds >
Editor "1" --- "1..*" City : adds >
Player "1" --- "1..*" Station : builds / upgrades / lists >
Player "1" --- "1" RailwayLine : builds >
Player "1" --- "1..*" Locomotive : buys >
Player "1" --- "1..*" Train : assigns / lists >
ProductOwner "1" --- "1" Simulator : creates >
Map "1" --- "1..*" City : contains >



@enduml