@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Player" as Employee
participant ":System" as System

activate Employee

    Employee -> System : requests to create a new simulation
    activate System

        System --> Employee : displays list of available scenarios\nand asks to select one
    deactivate System

    Employee -> System : selects a scenario
    activate System

        System -> System : identifies all existing stations\nin the railway network
        System -> System : verifies cities and industries\nassociated with each station
        System -> System : generates cargo based on\nsupply and demand rules
        System --> Employee : shows generated data and\nrequests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : starts simulation and\nconfirms operation success
    deactivate System

@enduml
