@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

class Player {
    - budget : double
}

class UpgradeStationUI {
    + getStationsAvailableForUpgrade() : List<Station>
    + getAvailableUpgradeBuildings(station : Station) : List<UpgradeBuilding>
    + applyUpgrade(station : Station, upgradeBuilding : UpgradeBuilding) : boolean
}

class UpgradeStationController {
    + getStationsAvailableForUpgrade() : List<Station>
    + getAvailableUpgradeBuildings(station : Station) : List<UpgradeBuilding>
    + applyUpgrade(station : Station, upgradeBuilding : UpgradeBuilding) : boolean
}

class StationRepository {
    + getStationsAvailableForUpgrade() : List<Station>
}

class UpgradeBuildingRepository {
    + getAvailableUpgradeBuildings(station : Station, installedUpgradesList : List<UpgradeBuilding>, currentDate : Date) : List<UpgradeBuilding>
}

class Station {
    - name : String
    - type : String
    - economicRadius : double
    - cost : double
    - supply : double
    - demand : double
    + getUpgradesInstalled() : List<UpgradeBuilding>
    + replaceBuilding(installedUpgrade : UpgradeBuilding, upgradeBuilding : UpgradeBuilding) : boolean
    + addBuilding(upgradeBuilding : UpgradeBuilding) : boolean
}

class UpgradeBuilding {
    - type : String
    - availabilityDate : Date
    - exclusivityGroup : String
    + isInSameExclusivityGroup(upgradeBuilding : UpgradeBuilding) : boolean
}

class Scenario {
    + getCurrentDate() : Date
}

Player --> "*" Station : upgrades >
Station --> "*" UpgradeBuilding : upgraded with >
UpgradeStationUI --> UpgradeStationController
UpgradeStationController --> StationRepository
UpgradeStationController --> UpgradeBuildingRepository
UpgradeStationController --> Scenario
StationRepository --> "*" Station : stations
UpgradeBuildingRepository --> "*" UpgradeBuilding : upgradeBuildings

@enduml