@startuml
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

class ListStationUI {
}

class ListStationController {
    + getAllStations() : List<StationDTO>
    + getStationDetails(stationID : String) : StationDetailsDTO
}

interface IRepositories {
    + getStationRepository() : IStationRepository
}
class Repositories implements IRepositories {
    - Repositories()
    + {static} getInstance() : Repositories
    + getStationRepository() : IStationRepository
}

interface IStationRepository {
    + getAllStations() : List<Station>
    + getStationByID(stationID : String) : Station
}
class StationRepository implements IStationRepository {
    + getAllStations() : List<Station>
    + getStationByID(stationID : String) : Station
}

interface IStationMapper {
    + toDTO(stationList : List<Station>) : List<StationDTO>
    + toDTO(station : Station) : StationDTO
    + toDetailsDTO(station : Station) : StationDetailsDTO
}
class StationMapper implements IStationMapper {
    + toDTO(stationList : List<Station>) : List<StationDTO>
    + toDTO(station : Station) : StationDTO
    + toDetailsDTO(station : Station) : StationDetailsDTO
}

class Station {
    - name : String
    - type : String
    - economicRadius : double
    - performance : double
    - cost : double
    - supply : double
    - demand : double
    + getStationDetails() : StationDetails
}

class StationDTO {
}

class StationDetailsDTO {
    + name : String
    + type : String
    + economicRadius : double
    + performance : double
    + supply : double
    + demand : double
}

ListStationUI ..> ListStationController
ListStationController ..> IRepositories
Repositories ..|> IRepositories
Repositories --> IStationRepository
StationRepository ..|> IStationRepository
ListStationController ..> IStationRepository
ListStationController ..> IStationMapper
IStationMapper <|.. StationMapper
StationMapper ..> Station
StationMapper ..> StationDTO
StationMapper ..> StationDetailsDTO
IStationRepository <|.. StationRepository
StationRepository --> "*" Station : stations

Repositories -> "1" Repositories : instance

@enduml